version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/var/www
    networks:
      - laravel_net

networks:
  laravel_net:
    external: true
