server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values:
              - ".+" # THIS IS THE CRUCIAL CHANGE: the regex is now a direct string in the list
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
      - source_labels: ['__meta_docker_container_id']
        target_label: container_id
      - source_labels: ['__meta_docker_container_image']
        target_label: image
      - source_labels: ['__meta_docker_container_name']
        action: replace
        target_label: job
        replacement: '${1}'
      - source_labels: ['__meta_docker_log_stream']
        target_label: log_stream
      - source_labels: ['__meta_docker_network_mode']
        target_label: network_mode
      - source_labels: ['__meta_docker_service_name']
        target_label: service_name
      - source_labels: ['__meta_docker_container_hostname']
        target_label: hostname
